// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "email1@example.com",
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            Phone = "123-456-7801",
                            Position = "Position1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "email2@example.com",
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            Phone = "123-456-7802",
                            Position = "Position2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "email3@example.com",
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            Phone = "123-456-7803",
                            Position = "Position3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "email4@example.com",
                            FirstName = "FirstName4",
                            LastName = "LastName4",
                            Phone = "123-456-7804",
                            Position = "Position4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "email5@example.com",
                            FirstName = "FirstName5",
                            LastName = "LastName5",
                            Phone = "123-456-7805",
                            Position = "Position5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "email6@example.com",
                            FirstName = "FirstName6",
                            LastName = "LastName6",
                            Phone = "123-456-7806",
                            Position = "Position6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "email7@example.com",
                            FirstName = "FirstName7",
                            LastName = "LastName7",
                            Phone = "123-456-7807",
                            Position = "Position7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "email8@example.com",
                            FirstName = "FirstName8",
                            LastName = "LastName8",
                            Phone = "123-456-7808",
                            Position = "Position8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "email9@example.com",
                            FirstName = "FirstName9",
                            LastName = "LastName9",
                            Phone = "123-456-7809",
                            Position = "Position9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "email10@example.com",
                            FirstName = "FirstName10",
                            LastName = "LastName10",
                            Phone = "123-456-7810",
                            Position = "Position10"
                        },
                        new
                        {
                            Id = 11,
                            Email = "email11@example.com",
                            FirstName = "FirstName11",
                            LastName = "LastName11",
                            Phone = "123-456-7811",
                            Position = "Position11"
                        },
                        new
                        {
                            Id = 12,
                            Email = "email12@example.com",
                            FirstName = "FirstName12",
                            LastName = "LastName12",
                            Phone = "123-456-7812",
                            Position = "Position12"
                        },
                        new
                        {
                            Id = 13,
                            Email = "email13@example.com",
                            FirstName = "FirstName13",
                            LastName = "LastName13",
                            Phone = "123-456-7813",
                            Position = "Position13"
                        },
                        new
                        {
                            Id = 14,
                            Email = "email14@example.com",
                            FirstName = "FirstName14",
                            LastName = "LastName14",
                            Phone = "123-456-7814",
                            Position = "Position14"
                        },
                        new
                        {
                            Id = 15,
                            Email = "email15@example.com",
                            FirstName = "FirstName15",
                            LastName = "LastName15",
                            Phone = "123-456-7815",
                            Position = "Position15"
                        },
                        new
                        {
                            Id = 16,
                            Email = "email16@example.com",
                            FirstName = "FirstName16",
                            LastName = "LastName16",
                            Phone = "123-456-7816",
                            Position = "Position16"
                        },
                        new
                        {
                            Id = 17,
                            Email = "email17@example.com",
                            FirstName = "FirstName17",
                            LastName = "LastName17",
                            Phone = "123-456-7817",
                            Position = "Position17"
                        },
                        new
                        {
                            Id = 18,
                            Email = "email18@example.com",
                            FirstName = "FirstName18",
                            LastName = "LastName18",
                            Phone = "123-456-7818",
                            Position = "Position18"
                        },
                        new
                        {
                            Id = 19,
                            Email = "email19@example.com",
                            FirstName = "FirstName19",
                            LastName = "LastName19",
                            Phone = "123-456-7819",
                            Position = "Position19"
                        },
                        new
                        {
                            Id = 20,
                            Email = "email20@example.com",
                            FirstName = "FirstName20",
                            LastName = "LastName20",
                            Phone = "123-456-7820",
                            Position = "Position20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
